sudo: required
language: python
group: deprecated-2017Q4
python:
    - "2.7"
env:
    - CKANVERSION=2.5.6 POSTGISVERSION=2
    - CKANVERSION=2.6.3 POSTGISVERSION=2
    - CKANVERSION=2.7.0 POSTGISVERSION=2
    - CKANVERSION=2.8.3 POSTGISVERSION=2
services:
    - redis-server
    - postgresql
    - xvfb
addons:
    firefox: "46.0"
install:
    - bash bin/travis-build.bash
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
script: 
  - sh bin/travis-run.sh
after_success: coveralls
branches:
  only:
    - develop
