version: '2.3'

x-project:
  &project "${PROJECT}"

x-volumes:
  &default-volumes
  volumes:
    - /app/ckan ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    - ./ckanext:/app/ckanext:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    - ./test:/app/test:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    ##- /app/filestore # Override for environment without host mounts. Automatically uncommented in CI.

x-environment:
  &default-environment
  AMAZEEIO: AMAZEEIO
  no_proxy: "ckan,postgres,postgres-datastore,redis,solr,chrome,mailhog.docker.amazee.io"

services:

  ckan:
    build:
      context: .
      dockerfile: .docker/Dockerfile.ckan
      args:
        SITE_URL: "http://${PROJECT}.docker.amazee.io"
        CKAN_REPO:
        CKAN_VERSION:
    depends_on:
      - postgres
      - solr
    networks:
      - amazeeio-network
      - default
    ports:
      - "3000"
    image: *project
    <<: *default-volumes
    environment:
      <<: *default-environment
      AMAZEEIO_HTTP_PORT: 3000
      LAGOON_LOCALDEV_URL: "http://${PROJECT}.docker.amazee.io"
      AMAZEEIO_URL: "${PROJECT}.docker.amazee.io"

  postgres:
    image: amazeeio/postgres-ckan
    ports:
      - "5432"
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment

  postgres-datastore:
    image: amazeeio/postgres-ckan
    ports:
      - "5432"
    networks:
      - amazeeio-network
      - default
    environment:
      <<: *default-environment

  redis:
    image: redis:6-alpine
    environment:
      <<: *default-environment
    networks:
      - amazeeio-network
      - default

  solr:
    image: ckan/ckan-solr-dev:2.8
    ports:
      - "8983"
    environment:
      <<: *default-environment
    networks:
      - amazeeio-network
      - default

  chrome:
    image: selenium/standalone-chrome:3.141.59-oxygen
    shm_size: '1gb'
    depends_on:
      - ckan
    <<: *default-volumes
    environment:
      <<: *default-environment
    networks:
      - amazeeio-network
      - default

volumes:
  solr-data: {}

networks:
  amazeeio-network:
    external: true
